# Generated by Django 5.0.6 on 2024-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet_balance',
            field=models.IntegerField(default=0),
        ),
    ]
