# Generated by Django 5.0.6 on 2024-06-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
    ]
