# Generated by Django 5.0.6 on 2024-06-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='add_money',
            field=models.IntegerField(default=0),
        ),
    ]
