# Generated by Django 5.0.6 on 2024-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customer_wallet_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet_balance',
            field=models.IntegerField(default=0),
        ),
    ]
