# Generated by Django 5.0.6 on 2024-06-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cart_customer_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
