# Generated by Django 5.0.6 on 2024-06-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='wl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.wishlist'),
        ),
    ]
