# Generated by Django 5.0.6 on 2024-06-18 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_seller_coupon_vendor'),
        ('users', '0013_alter_customer_add_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor'),
        ),
    ]
