services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 ecommerce.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - env.dev
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.dev

volumes:
  postgres_data:
  static_volume:
  media_volume:
