version: '3.8'

services:
  web:
    build: ./ecommerce
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ecommerce/:/usr/src/ecommerce/
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passpostgres
